export const PLATFORMS = [
  {
    id: 1,
    name: 'GitHub',
    ImageURL: '../assets/images/icon-github-gray.svg',
    validUrl: /^https:\/\/github\.com\/.+$/,
  },
  {
    id: 2,
    name: 'Frontend Mentor',
    ImageURL: '../assets/images/icon-frontend-mentor-gray.svg',
    validUrl: /^https:\/\/www\.frontendmentor\.io\/.+$/,
  },
  {
    id: 3,
    name: 'Twitter',
    ImageURL: '../assets/images/icon-twitter-gray.svg',
    validUrl: /^https:\/\/twitter\.com\/.+$/,
  },
  {
    id: 4,
    name: 'LinkedIn',
    ImageURL: '../assets/images/icon-linkedin-gray.svg',
    validUrl: /^https:\/\/www\.linkedin\.com\/.+$/,
  },
  {
    id: 5,
    name: 'YouTube',
    ImageURL: '../assets/images/icon-youtube-gray.svg',
    validUrl: /^https:\/\/www\.youtube\.com\/.+$/,
  },
  {
    id: 6,
    name: 'Facebook',
    ImageURL: '../assets/images/icon-facebook-gray.svg',
    validUrl: /^https:\/\/www\.facebook\.com\/.+$/,
  },
  {
    id: 7,
    name: 'Codepen',
    ImageURL: '../assets/images/icon-codepen-gray.svg',
    validUrl: /^https:\/\/codepen\.io\/.+$/,
  },
  {
    id: 8,
    name: 'Twitch',
    ImageURL: '../assets/images/icon-twitch-gray.svg',
    validUrl: /^https:\/\/www\.twitch\.tv\/.+$/,
  },
  {
    id: 9,
    name: 'Devto',
    ImageURL: '../assets/images/icon-devto-gray.svg',
    validUrl: /^https:\/\/dev\.to\/.+$/,
  },
  {
    id: 10,
    name: 'Codewars',
    ImageURL: '../assets/images/icon-codewars-gray.svg',
    validUrl: /^https:\/\/www\.codewars\.com\/.+$/,
  },
  {
    id: 11,
    name: 'Hashnode',
    ImageURL: '../assets/images/icon-hashnode-gray.svg',
    validUrl: /^https:\/\/hashnode\.com\/.+$/,
  },
  {
    id: 12,
    name: 'FreeCodeCamp',
    ImageURL: '../assets/images/icon-freecodecamp-gray.svg',
    validUrl: /^https:\/\/www\.freecodecamp\.org\/.+$/,
  },
  {
    id: 13,
    name: 'GitLab',
    ImageURL: '../assets/images/icon-gitlab-gray.svg',
    validUrl: /^https:\/\/gitlab\.com\/.+$/,
  },
  {
    id: 14,
    name: 'Stack Overflow',
    ImageURL: '../assets/images/icon-stack-overflow-gray.svg',
    validUrl: /^https:\/\/stackoverflow\.com\/.+$/,
  },
];
