export const PLATFORMS = [
  {
    id: 1,
    name: 'GitHub',
    ImageURL: '../assets/images/icon-github-gray.svg',
    color: '#24292e',
  },
  {
    id: 2,
    name: 'Frontend Mentor',
    ImageURL: '../assets/images/icon-frontend-mentor-gray.svg',
    color: '#20232a',
  },
  {
    id: 3,
    name: 'Twitter',
    ImageURL: '../assets/images/icon-twitter-gray.svg',
    color: '#1da1f2',
  },
  {
    id: 4,
    name: 'LinkedIn',
    ImageURL: '../assets/images/icon-linkedin-gray.svg',
    color: '#0a66c2',
  },
  {
    id: 5,
    name: 'YouTube',
    ImageURL: '../assets/images/icon-youtube-gray.svg',
    color: '#ff0000',
  },
  {
    id: 6,
    name: 'Facebook',
    ImageURL: '../assets/images/icon-facebook-gray.svg',
    color: '#1877f2',
  },
  {
    id: 7,
    name: 'Codepen',
    ImageURL: '../assets/images/icon-codepen-gray.svg',
    color: '#000000',
  },
  {
    id: 8,
    name: 'Twitch',
    ImageURL: '../assets/images/icon-twitch-gray.svg',
    color: '#9146ff',
  },
  {
    id: 9,
    name: 'Devto',
    ImageURL: '../assets/images/icon-devto-gray.svg',
    color: '#0a0a0a',
  },
  {
    id: 10,
    name: 'Codewars',
    ImageURL: '../assets/images/icon-codewars-gray.svg',
    color: '#b1361e',
  },
  {
    id: 11,
    name: 'Hashnode',
    ImageURL: '../assets/images/icon-hashnode-gray.svg',
    color: '#2962ff',
  },
  {
    id: 12,
    name: 'FreeCodeCamp',
    ImageURL: '../assets/images/icon-freecodecamp-gray.svg',
    color: '#006400',
  },
  {
    id: 13,
    name: 'GitLab',
    ImageURL: '../assets/images/icon-gitlab-gray.svg',
    color: '#fc6d26',
  },
  {
    id: 14,
    name: 'Stack Overflow',
    ImageURL: '../assets/images/icon-stack-overflow-gray.svg',
    color: '#f48024',
  },
];
